option 7 is no longer supported
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] error: Source option 7 is no longer supported. Use 8 or later.
[ERROR] error: Target option 7 is no longer supported. Use 8 or later.